// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8I8ENNal-ye7SzhMTadjobgMIFdBnyQE',
    appId: '1:392502074075:web:fa5ac36106b377caabcafe',
    messagingSenderId: '392502074075',
    projectId: 'xpense-track-e2a4f',
    authDomain: 'xpense-track-e2a4f.firebaseapp.com',
    storageBucket: 'xpense-track-e2a4f.firebasestorage.app',
    measurementId: 'G-6H7VX916L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf68syaLdqgzwkWMuzVj-BEV30ai5a-_4',
    appId: '1:392502074075:android:c21824bd99583033abcafe',
    messagingSenderId: '392502074075',
    projectId: 'xpense-track-e2a4f',
    storageBucket: 'xpense-track-e2a4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsCYpFYuTR8zRsXJtAuFlG4YrC3200wM',
    appId: '1:392502074075:ios:ce8eaaaf3470144babcafe',
    messagingSenderId: '392502074075',
    projectId: 'xpense-track-e2a4f',
    storageBucket: 'xpense-track-e2a4f.firebasestorage.app',
    iosClientId:
        '392502074075-mednbj39rdhdlh274bii5291qcftqehg.apps.googleusercontent.com',
    iosBundleId: 'com.eshwar.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsCYpFYuTR8zRsXJtAuFlG4YrC3200wM',
    appId: '1:392502074075:ios:ce8eaaaf3470144babcafe',
    messagingSenderId: '392502074075',
    projectId: 'xpense-track-e2a4f',
    storageBucket: 'xpense-track-e2a4f.firebasestorage.app',
    iosClientId:
        '392502074075-mednbj39rdhdlh274bii5291qcftqehg.apps.googleusercontent.com',
    iosBundleId: 'com.eshwar.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8I8ENNal-ye7SzhMTadjobgMIFdBnyQE',
    appId: '1:392502074075:web:e118bbbcc3da0846abcafe',
    messagingSenderId: '392502074075',
    projectId: 'xpense-track-e2a4f',
    authDomain: 'xpense-track-e2a4f.firebaseapp.com',
    storageBucket: 'xpense-track-e2a4f.firebasestorage.app',
    measurementId: 'G-RE9GGCVW8F',
  );
}
